framework:
    rate_limiter:
        # Public API endpoints rate limiter: 3 requests per minute
        public_api:
            policy: 'sliding_window'
            limit: 3
            interval: '1 minute'

